package net.soomsam.zirmegghuette.zars.enums;

public enum NotificationType {
	NOTIFICATION_GROUPRESERVATION_ADD("NOTIFICATION_GROUPRESERVATION_ADD"), NOTIFICATION_GROUPRESERVATION_UPDATE("NOTIFICATION_GROUPRESERVATION_UPDATE"), NOTIFICATION_GROUPRESERVATION_DELETE("NOTIFICATION_GROUPRESERVATION_DELETE"),
	NOTIFICATION_USER_ADD("NOTIFICATION_USER_ADD"), NOTIFICATION_USER_UPDATE("NOTIFICATION_USER_UPDATE"), NOTIFICATION_USER_RESET("NOTIFICATION_USER_RESET"), NOTIFICATION_USER_ENABLE("NOTIFICATION_USER_ENABLE"), NOTIFICATION_USER_DISABLE("NOTIFICATION_USER_DISABLE");

	private final String notificationName;

	private NotificationType(final String notificationName) {
		this.notificationName = notificationName;
	}

	public String getNotificationName() {
		return notificationName;
	}
}
